name: Delete Old Workflow Runs
on:
  schedule:
    - cron: '10 0 1,15 * *'
  workflow_dispatch:

jobs:
  Delete_Runs:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@5bf9a1dac5c4d041c029f0a8370ddf0c5cb5aeb7 # v2.1.0
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 45
          keep_minimum_runs: 15
